### ISSUE TITLE
GitHub Actions - set-output command is deprecated

### ISSUE THREAD

**Issue by ubaid-ansari21** [bridgecrewio/checkov-action#105]
Hey Team,

I was working on chekcov github action and found the below warning. 

```Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ ```

Can we update action accordingly?

**Comment by gruebel** [comment]
hey @ubaid-ansari21 thanks for reaching out. It was already fixed and merged yesterday https://github.com/bridgecrewio/checkov/pull/3699 so it will be available with the next version.

**Comment by santhoshratala** [comment]
@gruebel,... I'm seeing the following error ever since the fix was updated,...
`Error: Unable to process file command 'output' successfully.
Error: Invalid format '       _               _              '`

after some digging, found this -> https://stackoverflow.com/questions/74137120/how-to-fix-or-avoid-error-unable-to-process-file-command-output-successfully

**Comment by vemulkri** [comment]
Hi, seeing same error `Error: Unable to process file command 'output' successfully.
Error: Invalid format '       _               _              '`

related to merge: https://github.com/bridgecrewio/checkov/pull/3710 .

**Comment by MrHash** [comment]
same here

**Comment by g0pinath** [comment]
> Hey Team,
> 
> I was working on chekcov github action and found the below warning.
> 
> `` Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ ``
> 
> Can we update action accordingly?

replacing uses: bridgecrewio/checkov-action@master with uses: bridgecrewio/checkov-action@v12.1810.0 works.

If they can merge this tag to master, then it should be restored to the way it worked last week

**Comment by torivara** [comment]
We are experiencing the same issue. After some initial testing I pinned to v12.1810.0, and this works as expected. Seems like something changed in v12.1811.0 that broke something. The v12 tag now points to a version that does not work.

We are using it to scan terraform_plans, and this worked fine until the latest version.

**Comment by gruebel** [comment]
fixed with the latest tag `v12.1814.0` and also `v12`
