### ISSUE TITLE
Update nodejs

### ISSUE THREAD

**Issue by ma-caylent** [bridgecrewio/checkov-action#109]
Hey! you are probably already aware of this, but nodejs12 is going to be deprecated soon

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout

**Comment by gruebel** [comment]
hey @ma-caylent thanks for reaching out. I'm not sure, what exactly we should update, because our action is Docker based and the used actions in our build are up-to-date.

**Comment by gruebel** [comment]
feel free to reach out with more info regarding this issue.
