### ISSUE TITLE
Add checkov version pin mechanism

### ISSUE THREAD

**Issue by twmartin** [bridgecrewio/checkov-action#11]
Some folks may wish to opt-in to `checkov` package updates within in CI pipelines on their own timeline. Some sort of version pin mechanism in this action would likely be appreciated by that crowd.

**Comment by schosterbarak** [comment]
interesting. do you have an example of a project that did it right and we can take inspiration from?

**Comment by twmartin** [comment]
I must admit that I'm pretty naive to Github Actions yet, but I did some searching and only found a single example as reference: https://github.com/marketplace/actions/ansible-lint; however, I don't particularly care for how that approach results in `ansible-lint` getting installed once in the Dockerfile at the latest version, then a second time in the entrypoint at the pinned version. I suspect that the lack of examples may be due to the relative immaturity of Github Actions.

I feel like an alternative approach, which could arguably be more elegant would be to tie the `checkov` releases into a `checkov-action` workflow. For example, the `checkov` `publish-package` job (https://github.com/bridgecrewio/checkov/blob/master/.github/workflows/build.yml#L72) completes and triggers a new `checkov-action` workflow remotely (perhaps https://github.community/t5/GitHub-Actions/Triggering-by-other-repository/m-p/30688#M512), which could update the repo `Dockerfile` along the lines of `RUN pip install checkov==<old-version>` -> `RUN pip install checkov==<new-version>`, then an automated release of the action could follow.

**Comment by cmavr8** [comment]
I might be misunderstanding the request, but what if you pin the version used in the yml file used by Actions?

For example, instead of using 
`        uses: bridgecrewio/checkov-action@master`
you would use
`        uses: bridgecrewio/checkov-action@v11`

See [last line of Readme](https://github.com/bridgecrewio/checkov-action/blob/master/README.md#example-usage).

**Comment by twmartin** [comment]
@cmavr8 - we did have the action pinned to v10, but I believe the `RUN pip install -U checkov` at https://github.com/bridgecrewio/checkov-action/blob/master/Dockerfile#L6 results in the latest version of the `checkov` being pulled for every action run.

**Comment by cmavr8** [comment]
In case it wasn't clear: I agree with you, my suggestion doesn't solve the issue.

**Comment by schosterbarak** [comment]
done! take a look on the github action on this: https://github.com/bridgecrewio/checkov-action/blob/master/.github/workflows/build.yml

**Comment by twmartin** [comment]
> done! take a look on the github action on this: https://github.com/bridgecrewio/checkov-action/blob/master/.github/workflows/build.yml

This looks super slick!
