### ISSUE TITLE
Have problems with using

### ISSUE THREAD

**Issue by kobrikx** [bridgecrewio/checkov-action#12]
Hello! When i try to use your action - it cannot make dockerfile image with this error: 

 ```
Step 2/5 : RUN pip install -r requirements.txt
75
 ---> Running in 5f522fb0712e
76
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
77
The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
```

**Comment by schosterbarak** [comment]
Hey I just pushed a fix, can you try again?

**Comment by kobrikx** [comment]
<img width="951" alt="Снимок экрана 2020-06-03 в 18 34 31" src="https://user-images.githubusercontent.com/24703846/83657092-16568580-a5c9-11ea-8aa6-918b4d3152c3.png">

**Comment by schosterbarak** [comment]
thanks! fixed :)
