### ISSUE TITLE
Checkov adopting root permissions in Github Actions Runs when creating results folder, cannot clean itself up afterwards

### ISSUE THREAD

**Issue by imartinKeeper** [bridgecrewio/checkov-action#143]
We're using the following snippet in one of our repos to do some basic checking w/ this action:
```      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./${{ matrix.module }}
          output_format: cli,sarif
          output_file_path: console,results/${{ matrix.module }}.sarif
```
          
However, when it generates the results folder,  that folder has root permissions, despite the fact that github actions runs as the base user.

We're running this on a self-hosted runner, and this can cause intermittent failures between runs as we can't clean these up during runtime, but have to manually go into the server to fix it.

**Comment by gruebel** [comment]
Not sure how exactly I can help, but this is how GitHub expects it to be https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions#user

> Docker actions must be run by the default Docker user (root). Do not use the USER instruction in your Dockerfile, because you won't be able to access the GITHUB_WORKSPACE directory.
