### ISSUE TITLE
Checkov GitHub Action Reports SKIPPED Findings as Warnings

### ISSUE THREAD

**Issue by jpiazza35** [bridgecrewio/checkov-action#145]
Issue Description:
I am using the Checkov GitHub Action to scan my Terraform code for best practices and security vulnerabilities. I have successfully added #checkov:skip=CHECK_ID comments to skip certain checks that are not applicable to my use case. However, I have noticed that these skipped findings are still being reported as warnings in the GitHub Actions output.

Steps to Reproduce:
Add #checkov:skip=CHECK_ID: "Reason for skipping" above a resource block in a Terraform file.
Run the Checkov GitHub Action on the repository.
Observe that the skipped findings are still reported as warnings in the GitHub Actions output.

Expected Behavior:
The skipped findings should be completely omitted from the report or should not appear as warnings.

Actual Behavior:
The skipped findings are reported as warnings in the GitHub Actions output.

Configuration:
I am running the Checkov GitHub Action with the following configuration:

yaml
Copy code
name: Running Checkov tool for analysis
on:
  workflow_call:
    ...
jobs:
  build:
    ...
      - name: Test with Checkov
        id: checkov
        continue-on-error: true
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
          skip_check: '${{ inputs.skip_check }}'
          soft_fail: false
          output_format: 'junitxml, cli'
          output_file_path: '${{ inputs.directory }}'

Relevant Logs:

`
Check: CKV2_AWS_5: "Ensure that Security Groups are attached to another resource"
	SKIPPED for resource: module.eks_mgmt.aws_security_group.eks_node_group_sg
	Suppress comment: No comment provided
	File: /eks_cluster/modules/1_eks/ec2-security-groups.tf:2-33
	Guide: https://docs.paloaltonetworks.com/content/techdocs/en_US/prisma/prisma-cloud/prisma-cloud-code-security-policy-reference/aws-policies/aws-networking-policies/ensure-that-security-groups-are-attached-to-ec2-instances-or-elastic-network-interfaces-enis.html
Check: CKV2_AWS_5: "Ensure that Security Groups are attached to another resource"
	SKIPPED for resource: module.eks_mgmt.module.eks.aws_security_group.cluster[0]
	Suppress comment:  "Skipping this check because this is an external module. and we do not manage it"
	File: /eks_cluster/modules/terraform-aws-eks-rd-master/main.tf:184-202
	Guide: https://docs.paloaltonetworks.com/content/techdocs/en_US/prisma/prisma-cloud/prisma-cloud-code-security-policy-reference/aws-policies/aws-networking-policies/ensure-that-security-groups-are-attached-to-ec2-instances-or-elastic-network-interfaces-enis.html
Check: CKV2_AWS_5: "Ensure that Security Groups are attached to another resource"
	SKIPPED for resource: module.eks_mgmt.module.eks.aws_security_group.node[0]
	Suppress comment:  "Skipping this check because this is an external module. and we do not manage it"
	File: /eks_cluster/modules/terraform-aws-eks-rd-master/node_groups.tf:186-207
	Guide: https://docs.paloaltonetworks.com/content/techdocs/en_US/prisma/prisma-cloud/prisma-cloud-code-security-policy-reference/aws-policies/aws-networking-policies/ensure-that-security-groups-are-attached-to-ec2-instances-or-elastic-network-interfaces-enis.html`

![image](https://github.com/bridgecrewio/checkov-action/assets/36086658/d0b7e6fe-fd75-49fb-a484-d4b0b5652123)

all of these bel;ow warning were errors , after to comment them in the code , they disappear as error but still appearing as warning , why is this ? i need them be removed from report
![image](https://github.com/bridgecrewio/checkov-action/assets/36086658/aa464fc8-b13e-4d48-8451-2f078968c751)

**Comment by jpiazza35** [comment]
some updates on this ??

**Comment by gruebel** [comment]
hey @jpiazza35 thanks for reaching out.

This behaviour is in-place for quite a long time and therefore we don't plan on changing it anytime soon.
