### ISSUE TITLE
scan only changes in new PR compared to main in actions flow

### ISSUE THREAD

**Issue by anemiroffsumer** [bridgecrewio/checkov-action#169]
Is there anyway to have a github actions flow only scan for changes that are introduced in a PR as opposed to scanning the entire codebase in the PR ?

**Comment by mattias-hofvander** [comment]
The direct integration with GitHub would report on only changed resources in a PR, is there any way this could be achieved with the checkov-action?

**Comment by Saarett** [comment]
Hi,
As we see there’s not much engagement for this request, we aren’t planning on implementing it ourselves. However, we would be glad to receive a contribution and would happily assist.
For now, I’m closing the thread.
