### ISSUE TITLE
Whitelist for Checkov failures

### ISSUE THREAD

**Issue by jkataja** [bridgecrewio/checkov-action#2]
I would like to configure which failing checks do not cause the action to fail. For instance, to whitelist the rule CKV_AWS_24: "Ensure no security groups allow ingress from 0.0.0.0:0 to port 22"

**Comment by schosterbarak** [comment]
Hi @jkataja  you can suppress/skip checkov checks using the following syntax:
https://www.checkov.io/2.Concepts/Suppressions.html
