### ISSUE TITLE
"Latest" release (v13) from June 2020 gets picked up by Dependabot

### ISSUE THREAD

**Issue by pndurette** [bridgecrewio/checkov-action#21]
Hi,

We're using Dependabot for GitHub Actions and it keeps wanting to update to `bridgecrewio/checkov-action@v13`, which is tagged as `latest` in GitHub and the Marketplace, (and/or is the highest, not sure what Dependabot looks for), when in fact it is from June 2020. 

Is it possible to remove this tag? Or at least update the `latest` with each new release?
Not a blocker since we can always tell Dependabot not to update or set a version constraint, however.

Thanks for the great work!

**Comment by metahertz** [comment]
Hey @pndurette! Thanks for reporting this. Just checking for some history on V13, but looks like we can just scrap the tag!

**Comment by metahertz** [comment]
Deleted the v13 tag @pndurette  :) Let us know if this doesnt solve your dependabot issues!

**Comment by jamiepedwards** [comment]
@metahertz i still see the v13 tag and am having the same issue as @pndurette - just noticed that we have a whole bunch of projects that are using this >year old version because Dependabot picked it up.  I don't think this is resolved.
