### ISSUE TITLE
Turn off failure for warnings

### ISSUE THREAD

**Issue by efernandes-dev-ops** [bridgecrewio/checkov-action#29]
Is there a way to turn off the failure for warnings? So rather than skipping the check, would rather just display the warning.

For example:

Check: CKV_AWS_40: "Ensure IAM policies are attached only to groups or roles (Reducing access management complexity may in-turn reduce opportunity for a principal to inadvertently receive or retain excessive privileges.)"
	FAILED for resource: aws_iam_user_policy.iam_user_policy
Warning: 	File: /terraform/iam.tf:8-15
	Guide: https://docs.bridgecrew.io/docs/iam_16-iam-policy-privileges-1

**Comment by JamesWoolfenden** [comment]
You need the flag -- soft_fail

**Comment by efernandes-dev-ops** [comment]
But will that stop failures for all failed checks though - I saw the comment in the file that stated 

soft_fail: true # optional: do not return an error code if there are failed checks 

or will not return an error code for warning only?

will try it

**Comment by JamesWoolfenden** [comment]
I believe it affects the error code

**Comment by efernandes-dev-ops** [comment]
I am re-opening this issue as soft_fail just ignores all errors, if we are ignoring all errors there is no point in using checkov in the first place.

Here is an example of us using soft fail - 

```
terraform scan results:

Passed checks: 119, Failed checks: 1, Skipped checks: 0

Check: CKV_AWS_111: "Ensure IAM policies does not allow write access without constraints"
	FAILED for resource: module.sso.aws_iam_policy_document.accounts_payable_policy
Error: 	File: /terraform/policy.tf:1-35
	Calling File: /terraform/sso.tf:1-3

		1  | data "aws_iam_policy_document" "accounts_payable_policy" {
		2  | 
		3  |   statement {
		4  |     sid     = "DenyAccountRolesPolices"
		5  |     effect  = "Deny"
		6  |     actions = ["iam:*"]
		7  |     resources = [
		8  |       "arn:aws:iam::*:role/${local.policy_path}/*",
		9  |       "arn:aws:iam::*:policy/${local.policy_path}/*"
		10 |     ]
		11 |   }
		12 | 
		13 |   statement {
		14 |     sid     = "AllowAssumeBilling"
		15 |     effect  = "Allow"
		16 |     actions = ["sts:AssumeRole"]
		17 |     resources = concat([
		18 |       for account_name, account in local.account_map : "arn:aws:iam::${account}:role/${local.policy_path}/Billing"
		19 |       ],
		20 |       ["arn:aws:iam::${lookup(local.account_map, local.AWS_ACCOUNT_LEGACY)}:role/${local.policy_path}/ReadOnly"]
		21 | 
		22 |     )
		23 |   }
		24 | 
		25 |   statement {
		26 |     sid    = "VisualEditor0"
		27 |     effect = "Allow"
		28 |     actions = [
		29 |       "aws-portal:ViewBilling",
		30 |       "aws-portal:ViewUsage",
		31 |     "support:*"]
		32 | 
		33 |     resources = ["*"]
		34 |   }
		35 | }
```

**Comment by JamesWoolfenden** [comment]
If you want to suppress individual rules try using --skip-check SKIP_CHECK at the cli or add the suppression.
