### ISSUE TITLE
Download failed Github Action

### ISSUE THREAD

**Issue by ArneRiemann4711** [bridgecrewio/checkov-action#42]
Howdy,

again GitHub Actions failed to Download checkov action (-:

```
Warning: Failed to download action 'https://api.github.com/repos/bridgecrewio/checkov-action/tarball/3aaa4552f91bedf8255f71770de869a0a8035205'. Error: Response status code does not indicate success: 403 (Forbidden).
Warning: Back off 26.798 seconds before retry.
```

**Comment by gpaquet85** [comment]
Same issue on our side. Interested to know if action is possible to fix it ;)

**Comment by schosterbarak** [comment]
hey @gpaquet85 @ArneRiemann4711 can you try now?

**Comment by gpaquet85** [comment]
It looks ok now Thanks for your support @schosterbarak ;)

**Comment by ArneRiemann4711** [comment]
Works again thx @schosterbarak

**Comment by apinzo1** [comment]
Reporting this issue again... 
<img width="1044" alt="Screen Shot 2021-07-01 at 10 40 15 AM" src="https://user-images.githubusercontent.com/55505682/124154070-bb58c180-da5a-11eb-8535-345337e0f7d0.png">
