### ISSUE TITLE
Github Action Docker build failing at pip install missing requirements.txt v12.0.1

### ISSUE THREAD

**Issue by dhishan** [bridgecrewio/checkov-action#43]
[checkov.log](https://github.com/bridgecrewio/checkov-action/files/6511861/checkov.log)

**Comment by dhishan** [comment]
Actually it works with master, but by default when you install it uses the last release tag which is buggy - 12.0.1. Can you create a new release with the latest stable?

**Comment by nimrodkor** [comment]
So, we've had a lot of releases since 12.0.1. It was simply the only tag that was officially released on github. Should be fixed now, thanks for reporting @dhishan !
