### ISSUE TITLE
Feature Request: Add support for checkov config-file as parameter

### ISSUE THREAD

**Issue by mikelax** [bridgecrewio/checkov-action#45]
# Overview

As a devops build user, I would like to use a config-file checked in to source code to configure checkov instead of specifying values in the GitHub Action workflow step. 

Now that [checkov support a config-file](https://bridgecrew.io/blog/checkov-config-file-repeatably-support-multiple-environments/) for loading attributes, I should be able to specify a value for a single `config-file` parameter in order to configure checkov. 

## Open Questions

1. What happens if an attribute is specified in both the config-file and as a parameter to the workflow step? Does the value in the workflow file win, or is it easier to ignore those and only use the config file if one is specified. The answer to this question should be added to the documentation.

**Comment by sebastien-prudhomme** [comment]
Hi @mikelax, latest versions of the GitHub action have this option.

**Comment by mikelax** [comment]
nice! thanks @sebastien-prudhomme .
