### ISSUE TITLE
Add support for saving the output into a file and upload to github artifactory

### ISSUE THREAD

**Issue by nitishkumar1991** [bridgecrewio/checkov-action#51]
Needs the support to save scan results to a file corresponding to output format such as cli to txt, or github_failed_only to txt or junitxml to a xml file and upload to artifactory or repo itself.

**Comment by nmarchini** [comment]
I have this use case as well, the output_format option allows us to set JUNIT but there is now way to write the XML to a file so that we an then use another action (such as https://github.com/marketplace/actions/publish-unit-test-results ) to publish the test results in the Workflow summary.

**Comment by toast-gear** [comment]
Does it not put the results into `$CHECKOV_RESULTS` which you can then write to disk `echo "$CHECKOV_RESULTS" > results.xml`?

**Comment by mikelax** [comment]
Is this a duplicate of #30 ?

**Comment by gruebel** [comment]
this is possible via `output_file_path:`
