### ISSUE TITLE
Add support for skip-path

### ISSUE THREAD

**Issue by josh-barker** [bridgecrewio/checkov-action#55]
Hi,

I'd like to be able to specify to ignore a path in the action.

My terraform modules have the following directory structure:

```
./main.tf
./examples/default/main.tf
```

I'd like to run checkov on the root directory, but exclude the `examples` directory.

Cheers

**Comment by HariSekhon** [comment]
Use `skip-path` in `.checkov.yaml` - see my Templates repo for a working example that I use to skip scanning sub-modules:

https://github.com/HariSekhon/Templates/blob/master/.checkov.yaml

**Comment by josh-barker** [comment]
Hey @HariSekhon , thanks for your suggestion. I was hoping to set `skip-path` in the github action, instead of `.checkov.yaml`.

Cheers

**Comment by josh-barker** [comment]
Hey @HariSekhon, that's a nice pattern! Thanks for sharing! :-)
