### ISSUE TITLE
Major tag v12 is not updated

### ISSUE THREAD

**Issue by gofrolist** [bridgecrewio/checkov-action#63]
Major tag v12 is not updated and pointed to very old commit https://github.com/bridgecrewio/checkov-action/commits/v12

Regarding to official GitHub [recommendations](https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#recommendations) and [here](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management)

> Make the new release available to those binding to the major version tag: Move the major version tag (v1, v2, etc.) to point to the ref of the current release. This will act as the stable release for that major version. You should keep this tag updated to the most recent stable minor/patch release.

Because of that I can't use v12 tag and should point it to specific tag like v12.939.0 but it's updated quite frequently
```
      - name: Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@v12
```
Only way I can see it right now is use master branch which is not good for production usage
```
      - name: Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
```

**Comment by gofrolist** [comment]
You can use other GitHub actions like [actions-tagger](https://github.com/marketplace/actions/actions-tagger) or [update-major-minor-semver](https://github.com/marketplace/actions/update-major-minor-semver) for this purpose.

**Comment by schosterbarak** [comment]
@gofrolist we are always updating the tag. see: https://github.com/bridgecrewio/checkov-action/commits/v12.947.0

**Comment by sbe-arg** [comment]
Has been respolved can be closed now

**Comment by sbe-arg** [comment]
https://github.com/bridgecrewio/checkov-action/releases/tag/v12
