### ISSUE TITLE
Checkov-action unable to scan all the serverless.yml in root directory

### ISSUE THREAD

**Issue by Prashanthkool7** [bridgecrewio/checkov-action#65]
Hello Team,
Here is the my current checkov_scan.yml file
name: Run Checkov action serverless
id: checkov1
uses: bridgecrewio/checkov-action@master
with:
#skip_check: CKV_AWS_23 # optional: skip a specific check_id
#quiet: true # optional: display only failed checks
#log_level: DEBUG # optional: set log level. Default WARNING
output_format: cli # optional: the output format, one of: cli, json, junitxml, github_failed_only
framework: serverless
I have not mentioned directory path so that checkov scan both my terraform files and serverless.yml as well
but there are two files in the root directory serverless.yml and serverless-nonprod.yml
checkov is skipping the one of the file "serverless-nonprod.yml " if Irename the file from "serverless-nonprod.yml " to "serverless.yml" checkov is scanning.
is there way from github actions to pass a specific list of files to scan
I see there is an option checkov -f file name
but if i use github actions "bridgecrewio/checkov-action@master" i don't have any documentation to pass a file
can anyone please let me know how accomplish this.

**Comment by Prashanthkool7** [comment]
can you please enable file options so that we can able to scan multiple serverless-XXX.yml files

Checkov -f "filename 1, filename 2, filename 3"
 instead of checkov -d

**Comment by schosterbarak** [comment]
this issue is related to: https://github.com/bridgecrewio/checkov/issues/1904

**Comment by gruebel** [comment]
was implemented in `checkov`
