### ISSUE TITLE
Github Actions is broken

### ISSUE THREAD

**Issue by gavinjohnson-crowdcube** [bridgecrewio/checkov-action#74]
Since commit bb8d383 (https://github.com/bridgecrewio/checkov-action/commit/bb8d383b8d584be62a3bac0aac083fd87a8bc77f) the github actions is broken.  The 2.0.743 tag isn't published in the docker hub (https://hub.docker.com/r/bridgecrew/checkov/tags?page=1&name=2.0.743). Is it meant to be 2.0.742?

**Comment by tsmithv11** [comment]
Thank you for reporting! This has been fixed (updated to 2.0.744)
