### ISSUE TITLE
Github Action ignores baseline file

### ISSUE THREAD

**Issue by regel** [bridgecrewio/checkov-action#76]
**Describe the issue**

Running checkov in github action (runs docker image bridgecrew/checkov:2.0.756) ignores the baseline, outputs all errors, and exits with non-zero status code.

**Test 1**

The path to the baseline file is defined in checkov config file. Test is KO. Checkov runs, but reports all errors, as-if the baseline did not exist, and Github action fails due to non-zero status.

Content of the config file is:

```
branch: master
baseline: charts/cardano/.checkov.baseline
directory:
- charts/cardano
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
- helm
output:
- github_failed_only
skip-check:
- CKV_K8S_21
- CKV_K8S_10
- CKV_K8S_11
- CKV_K8S_12
- CKV_K8S_13
skip-path:
- /cardano/templates/tests/*
- /redis/*
```

Github Action [Logs](https://github.com/regel/cardano-charts/runs/4929499567?check_suite_focus=true) (truncated):

```
running checkov on directory: charts/cardano
checkov -d charts/cardano   --quiet  --output sarif   --config-file charts/cardano/.checkov    

       _               _              
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V / 
  \___|_| |_|\___|\___|_|\_\___/ \_/  
                                      
By bridgecrew.io | version: 2.0.756 
helm scan results:

Passed checks: 0, Failed checks: 24, Skipped checks: 0
```

**Test 2**

The path to the baseline is set in github action YAML settings. Test is KO. Checkov runs, but reports all errors, as-if the baseline did not exist, and Github action fails due to non-zero status.

Github Action [Logs](https://github.com/regel/cardano-charts/runs/4929182246?check_suite_focus=true) (truncated): 

```
running checkov on directory: charts/cardano
checkov -d charts/cardano   --quiet  --output sarif   --config-file charts/cardano/.checkov    --baseline charts/cardano/.checkov.baseline

       _               _              
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V / 
  \___|_| |_|\___|\___|_|\_\___/ \_/  
                                      
By bridgecrew.io | version: 2.0.756 
helm scan results:

Passed checks: 0, Failed checks: 24, Skipped checks: 0
```

**Test 3 (running the command line locally)**

```
$ checkov -d charts/cardano --baseline charts/cardano/.checkov.baseline --config-file charts/cardano/.checkov
| check_id   | file   | resource   | check_name   | guideline   |
|------------|--------|------------|--------------|-------------|


---


$ checkov --version
2.0.735
```

**Comment by nimrodkor** [comment]
Discussion is on the matching issue in checkov :), https://github.com/bridgecrewio/checkov/issues/2272

**Comment by regel** [comment]
I'm closing this one since the matching issue was resolved.
