### ISSUE TITLE
Docker pull limitations

### ISSUE THREAD

**Issue by iaacautomation** [bridgecrewio/checkov-action#86]
Since docker now has a limit pull is there a possibility of allowing a different docker image repo to be used instead of dockerhub? 

I am running into this issue

**Comment by gruebel** [comment]
hey @iaacautomation we now offer our `checkov` image in two different public image registries

- `bridgecrew/checkov` (Docker Hub)
- `ghcr.io/bridgecrewio/checkov` (GitHub Packages, which can be found [here]( https://github.com/bridgecrewio/checkov/pkgs/container/checkov))

we also changed the the GHA to use the GitHub Packages one and the Docker Hub one.
