### ISSUE TITLE
Provide a "v12" branch

### ISSUE THREAD

**Issue by ankon** [bridgecrewio/checkov-action#89]
We use the checkov-action to run checkov on our AWS/Terraform/GCP infrastructure definitions as a PR check, and it works great.

But, we are a bit hesitant to use the "master" version of the action (likelihood of incompatible changes), but at the same time have quite a bit of work to follow the specific minor/patch tags. Ideally we would like to point to "bridgecrewio/checkov-action@v12", where we would expect just the regular container version bumps. 

Implementation-wise: This would mean having a branch (or floating tag) pointing to the latest v12, and updating that whenever a minor/patch release of the v12 line is released.

What do you think, is this reasonable? Doable?

**Comment by sbe-arg** [comment]
https://github.com/bridgecrewio/checkov-action/pull/92

**Comment by sbe-arg** [comment]
This has been resolved

**Comment by sbe-arg** [comment]
https://github.com/bridgecrewio/checkov-action/releases/tag/v12

**Comment by ankon** [comment]
I'll close this issue as "resolved", thanks a lot, @sbe-arg!
