### ISSUE TITLE
Renovate's GitHub app worker blocked from looking up tags for this action

### ISSUE THREAD

**Issue by patheard** [bridgecrewio/checkov-action#97]
# Summary
We're using [renovatebot/renovate](https://github.com/renovatebot/renovate)'s GitHub app to manage our dependency updates.  Recently, we've noticed that Renovate can't lookup this action's tags, with the following error:
```javascript
"response": {
    "statusCode": 403,
    "statusMessage": "Forbidden",
    "body": {
        "message": "Although you appear to have the correct authorization credentials, the `bridgecrewio` organization has an IP allow list enabled, and 18.237.254.32 is not permitted to access this resource.",
    }
}
```

This used to work, so I'm guessing there's been a change to your GitHub org's IP allow list.  Any chance someone could look into this?

Here's the associated discussion with Renovate support:
https://github.com/renovatebot/renovate/discussions/17826

# Related
* #46

**Comment by gruebel** [comment]
hey @patheard thanks for reaching out. I answered inside the discussion thread. I don't see any problem on our side, either renovate changed something or GitHub did. This repo is public for any reads and we keep an IP whitelist for direct write permissions to it. This behaviour is in place for many months, so I don't think we can change anything and I don't understand why we should.

**Comment by patheard** [comment]
Yup, totally agree - I dug into it more and the responsibility is on the Renovate side to first safe-list their app's IP address:
https://github.com/renovatebot/renovate/discussions/17826#discussioncomment-3668839

If they did that, then it would be possible on your side to have your org allow those app IP address.

Thanks for looking into it.
